"""Phase 1 Mathematical Unit Tests for Prototype 3 (CBF-RL).

Audits and verifies:
1. Safety function h(s, v_ego)
2. CBF maximum acceleration bound u_cbf_max
3. Closed-form 1D CBF projection
4. Actuator infeasibility detection (u_cbf_max < u_min)
5. Forward Euler discrete kinematics and non-negativity clipping
6. Dual CBF reward calculation and anti-stalling reward check
7. Vicolungo exact lead replay: v_lead[k] == dataset Speed_LV[k]
8. Vicolungo closed-loop follower velocity generated by RL action (dataset Speed_FAV discarded)
9. Ablation isolation: Filter OFF does not allow u_safe to enter nominal reward
10. Ablation isolation: Filter ON nominal reward uses applied filtered action u_safe
11. Closed-loop environment execution across all 4 ablation modes
"""

import sys
from pathlib import Path
import numpy as np

# Ensure Prototype 3 directory is in Python path
sys.path.insert(0, str(Path(__file__).parent))

from config import Config
from cbf_core import (
    compute_h,
    compute_u_cbf_max,
    project_cbf,
    step_kinematics,
    compute_cbf_reward,
    compute_nominal_reward,
)
from env import CarFollowingEnv


def test_safety_barrier_h():
    """Verify h(s, v_ego) = s - (T_min * v_ego + D_min)."""
    cfg = Config()
    # 1. Safe state: s=50m, v=15m/s => 50 - (2*15 + 15) = 50 - 45 = +5m
    h_safe = compute_h(s=50.0, v_ego=15.0, T_min=cfg.T_min, D_min=cfg.D_min)
    assert abs(h_safe - 5.0) < 1e-9, f"Expected 5.0, got {h_safe}"

    # 2. Boundary state: s=45m, v=15m/s => 45 - 45 = 0.0m
    h_boundary = compute_h(s=45.0, v_ego=15.0, T_min=cfg.T_min, D_min=cfg.D_min)
    assert abs(h_boundary - 0.0) < 1e-9, f"Expected 0.0, got {h_boundary}"

    # 3. Unsafe state: s=30m, v=15m/s => 30 - 45 = -15m
    h_unsafe = compute_h(s=30.0, v_ego=15.0, T_min=cfg.T_min, D_min=cfg.D_min)
    assert abs(h_unsafe - (-15.0)) < 1e-9, f"Expected -15.0, got {h_unsafe}"

    # 4. Standstill state: s=20m, v=0m/s => 20 - 15 = +5m
    h_still = compute_h(s=20.0, v_ego=0.0, T_min=cfg.T_min, D_min=cfg.D_min)
    assert abs(h_still - 5.0) < 1e-9, f"Expected 5.0, got {h_still}"
    print("PASS: test_safety_barrier_h")


def test_u_cbf_max():
    """Verify u_cbf_max = (delta_v + alpha * h) / T_min."""
    cfg = Config()
    # 1. delta_v = 0, h = 10, alpha = 0.1, T_min = 2.0 => (0 + 1.0) / 2.0 = 0.5 m/s^2
    u_max_1 = compute_u_cbf_max(delta_v=0.0, h=10.0, T_min=cfg.T_min, alpha=cfg.alpha)
    assert abs(u_max_1 - 0.5) < 1e-9, f"Expected 0.5, got {u_max_1}"

    # 2. Lead driving faster: delta_v = +5, h = 10 => (5 + 1.0) / 2.0 = 3.0 m/s^2
    u_max_2 = compute_u_cbf_max(delta_v=5.0, h=10.0, T_min=cfg.T_min, alpha=cfg.alpha)
    assert abs(u_max_2 - 3.0) < 1e-9, f"Expected 3.0, got {u_max_2}"

    # 3. Lead braking: delta_v = -6, h = 10 => (-6 + 1.0) / 2.0 = -2.5 m/s^2
    u_max_3 = compute_u_cbf_max(delta_v=-6.0, h=10.0, T_min=cfg.T_min, alpha=cfg.alpha)
    assert abs(u_max_3 - (-2.5)) < 1e-9, f"Expected -2.5, got {u_max_3}"

    # 4. On the boundary: h = 0, delta_v = -4 => -4 / 2.0 = -2.0 m/s^2
    u_max_4 = compute_u_cbf_max(delta_v=-4.0, h=0.0, T_min=cfg.T_min, alpha=cfg.alpha)
    assert abs(u_max_4 - (-2.0)) < 1e-9, f"Expected -2.0, got {u_max_4}"
    print("PASS: test_u_cbf_max")


def test_cbf_projection():
    """Verify closed-form 1D projection onto the safe half-space."""
    cfg = Config()
    # Case 1: Policy action satisfies CBF and actuator bounds (no intervention)
    u_safe, intervened, infeasible = project_cbf(
        u_policy=0.0, u_cbf_max=1.0, u_min=cfg.u_min, u_max=cfg.u_max
    )
    assert abs(u_safe - 0.0) < 1e-9
    assert not intervened, "Should not intervene on compliant action"
    assert not infeasible, "Should be feasible"

    # Case 2: Policy action violates CBF bound (intervention required)
    u_safe, intervened, infeasible = project_cbf(
        u_policy=2.0, u_cbf_max=0.5, u_min=cfg.u_min, u_max=cfg.u_max
    )
    assert abs(u_safe - 0.5) < 1e-9, f"Expected u_safe=0.5, got {u_safe}"
    assert intervened, "Intervention flag must be True"
    assert not infeasible

    # Case 3: Policy action exceeds physical actuator max
    u_safe, intervened, infeasible = project_cbf(
        u_policy=3.0, u_cbf_max=4.0, u_min=cfg.u_min, u_max=cfg.u_max
    )
    assert abs(u_safe - 2.5) < 1e-9, f"Expected clamp to u_max=2.5, got {u_safe}"
    assert intervened
    assert not infeasible
    print("PASS: test_cbf_projection")


def test_actuator_infeasibility():
    """Verify handling when u_cbf_max < u_min (-4.0 m/s^2)."""
    cfg = Config()
    # Extreme closing speed: delta_v = -12 m/s, h = 5m
    # u_cbf_max = (-12 + 0.5) / 2.0 = -5.75 m/s^2 < -4.0 m/s^2
    u_cbf_max = compute_u_cbf_max(delta_v=-12.0, h=5.0, T_min=cfg.T_min, alpha=cfg.alpha)
    assert u_cbf_max == -5.75

    u_safe, intervened, infeasible = project_cbf(
        u_policy=-2.0, u_cbf_max=u_cbf_max, u_min=cfg.u_min, u_max=cfg.u_max
    )
    assert abs(u_safe - (-4.0)) < 1e-9, f"Expected emergency brake -4.0, got {u_safe}"
    assert intervened, "Intervention must occur"
    assert infeasible, "Infeasibility flag must be True when u_cbf_max < u_min"
    print("PASS: test_actuator_infeasibility")


def test_discrete_dynamics():
    """Verify forward Euler kinematics, non-negativity, and collision handling."""
    # 1. Standard kinematic step
    s1, v1, l1 = step_kinematics(s=40.0, v_ego=20.0, v_lead=20.0, u_applied=1.0, a_lead=0.0, dt=0.1)
    assert abs(v1 - 20.1) < 1e-9
    assert abs(l1 - 20.0) < 1e-9
    assert abs(s1 - 40.0) < 1e-9

    # 2. Non-negative velocity clipping (cannot reverse)
    s2, v2, l2 = step_kinematics(s=20.0, v_ego=0.2, v_lead=10.0, u_applied=-4.0, a_lead=0.0, dt=0.1)
    assert abs(v2 - 0.0) < 1e-9, f"v_ego must clip to 0.0, got {v2}"

    # 3. Collision clipping (s cannot become negative)
    s3, v3, l3 = step_kinematics(s=0.5, v_ego=25.0, v_lead=15.0, u_applied=0.0, a_lead=0.0, dt=0.1)
    # delta_s = (15 - 25) * 0.1 = -1.0m => 0.5 - 1.0 = -0.5m => clips to 0.0
    assert abs(s3 - 0.0) < 1e-9, f"s must clip to 0.0, got {s3}"

    # 4. Exogenous v_lead_next passing
    s4, v4, l4 = step_kinematics(s=40.0, v_ego=20.0, v_lead=20.0, u_applied=0.0, dt=0.1, v_lead_next=22.5)
    assert abs(l4 - 22.5) < 1e-9, f"Expected exact exogenous speed 22.5, got {l4}"
    print("PASS: test_discrete_dynamics")


def test_reward_calculation():
    """Verify CBF penalty behavior and anti-stalling reward check."""
    cfg = Config()

    # 1. Compliant action: r_cbf must be exactly 0.0
    r_cbf_safe, r1, r2 = compute_cbf_reward(
        u_policy=0.0, u_cbf_max=0.5, u_safe=0.0, w_cbf1=cfg.w_cbf1, w_cbf2=cfg.w_cbf2, sigma_sq=cfg.sigma_sq
    )
    assert abs(r_cbf_safe - 0.0) < 1e-9
    assert abs(r1 - 0.0) < 1e-9
    assert abs(r2 - 0.0) < 1e-9

    # 2. Non-compliant action: r_cbf must be negative
    # u_policy = 2.0, u_cbf_max = 0.5, u_safe = 0.5
    # psi = 0.5 - 2.0 = -1.5 => r_cbf1 = 1.0 * (-1.5) = -1.5
    r_cbf_viol, r1_v, r2_v = compute_cbf_reward(
        u_policy=2.0, u_cbf_max=0.5, u_safe=0.5, w_cbf1=cfg.w_cbf1, w_cbf2=cfg.w_cbf2, sigma_sq=cfg.sigma_sq
    )
    assert r_cbf_viol < -1.5, f"r_cbf should be heavily negative, got {r_cbf_viol}"
    assert abs(r1_v - (-1.5)) < 1e-9
    assert -2.0 <= r2_v <= 0.0, f"r2 must be bounded in [-2.0, 0.0], got {r2_v}"

    # 3. Anti-stalling check:
    # State A: Safe following at equilibrium (v_ego = 20, v_lead = 20, s = 2.5*20 + 18 = 68m)
    r_following, _ = compute_nominal_reward(
        s=68.0, v_ego=20.0, v_lead=20.0, u_action=0.0, u_prev=0.0, dt=cfg.dt,
        T_target=cfg.T_target, D_target=cfg.D_target, v_target=cfg.v_target,
        w_gap=cfg.w_gap, w_vel=cfg.w_vel, w_ctrl=cfg.w_ctrl, w_jerk=cfg.w_jerk,
        r_prog_max=cfg.r_prog_max, r_crash=cfg.r_crash, d_scale=cfg.d_scale,
        v_scale=cfg.v_scale, u_max=cfg.u_max, jerk_max=cfg.jerk_max,
        T_min=cfg.T_min, D_min=cfg.D_min,
    )

    # State B: Stalled at 0 m/s while lead vehicle drives away at 20 m/s
    r_stalled, _ = compute_nominal_reward(
        s=68.0, v_ego=0.0, v_lead=20.0, u_action=0.0, u_prev=0.0, dt=cfg.dt,
        T_target=cfg.T_target, D_target=cfg.D_target, v_target=cfg.v_target,
        w_gap=cfg.w_gap, w_vel=cfg.w_vel, w_ctrl=cfg.w_ctrl, w_jerk=cfg.w_jerk,
        r_prog_max=cfg.r_prog_max, r_crash=cfg.r_crash, d_scale=cfg.d_scale,
        v_scale=cfg.v_scale, u_max=cfg.u_max, jerk_max=cfg.jerk_max,
        T_min=cfg.T_min, D_min=cfg.D_min,
    )

    # Check that the selected safe following state has higher immediate reward
    # than this selected stalled state (without claiming global optimality)
    assert r_following > r_stalled, f"Expected r_following ({r_following:.3f}) > r_stalled ({r_stalled:.3f})"
    assert r_following > 0.0, f"r_following should be positive, got {r_following}"

    # 4. Terminal collision check
    r_collision, _ = compute_nominal_reward(
        s=0.0, v_ego=10.0, v_lead=10.0, u_action=0.0, u_prev=0.0, dt=cfg.dt,
        r_crash=cfg.r_crash
    )
    assert r_collision == cfg.r_crash, f"Expected crash penalty {cfg.r_crash}, got {r_collision}"
    print(f"PASS: test_reward_calculation (r_following={r_following:.3f} > r_stalled={r_stalled:.3f})")


def test_vicolungo_exact_lead_replay():
    """Verify A: In Vicolungo mode, v_lead[k] == dataset Speed_LV[k] exactly."""
    cfg = Config()
    env = CarFollowingEnv(config=cfg, mode="vicolungo", use_cbf_filter=True, use_cbf_reward=True)

    # Pick trajectory 1
    obs, info = env.reset(seed=1, options={"traj_id": 1})
    traj_df = env._vicolungo_trajs[1]
    expected_speeds = traj_df["Speed_LV"].to_numpy(dtype=float)

    # Check step 0
    assert abs(env.v_lead - expected_speeds[0]) < 1e-9, (
        f"Step 0: Expected v_lead={expected_speeds[0]}, got {env.v_lead}"
    )

    # Step forward 20 steps with varied actions and verify exact match at every step
    for k in range(20):
        action = np.array([0.2 if k % 2 == 0 else -0.3], dtype=np.float32)
        env.step(action)
        expected_k_plus_1 = expected_speeds[k + 1]
        assert abs(env.v_lead - expected_k_plus_1) < 1e-9, (
            f"Step {k+1}: Expected v_lead={expected_k_plus_1}, got {env.v_lead}"
        )
    print("PASS: test_vicolungo_exact_lead_replay (v_lead[k] == dataset Speed_LV[k] for all k)")


def test_vicolungo_closed_loop_follower_independence():
    """Verify B: Follower velocity is generated by applied RL action; dataset Speed_FAV is discarded."""
    cfg = Config()
    env = CarFollowingEnv(config=cfg, mode="vicolungo", use_cbf_filter=False, use_cbf_reward=False)

    obs, info = env.reset(seed=1, options={"traj_id": 1})
    traj_df = env._vicolungo_trajs[1]
    dataset_fav_speeds = traj_df["Speed_FAV"].to_numpy(dtype=float)

    # Step 0 matches initial dataset Speed_FAV
    assert abs(env.v_ego - dataset_fav_speeds[0]) < 1e-9

    # Apply maximum throttle action a = +1.0 => u_applied = +2.5 m/s^2
    action = np.array([1.0], dtype=np.float32)
    obs_next, reward, term, trunc, step_info = env.step(action)

    # Expected follower velocity is strictly computed from kinematics:
    expected_v_ego = max(0.0, dataset_fav_speeds[0] + 2.5 * cfg.dt)
    assert abs(env.v_ego - expected_v_ego) < 1e-9, (
        f"Expected simulated v_ego={expected_v_ego}, got {env.v_ego}"
    )

    # The simulated follower speed must NOT equal dataset Speed_FAV[1]
    # (unless by extreme coincidence dataset happened to accelerate at exactly 2.5 m/s^2)
    print(f"  Follower speed step 1: simulated={env.v_ego:.4f}, dataset_recorded={dataset_fav_speeds[1]:.4f}")
    assert abs(env.v_ego - dataset_fav_speeds[1]) > 1e-4, (
        "Simulated follower velocity should be driven by RL action, not dataset follower replay"
    )
    print("PASS: test_vicolungo_closed_loop_follower_independence")


def test_ablation_filter_off_nominal_reward_isolation():
    """Verify C: When Filter is OFF, u_safe does NOT enter nominal control/jerk reward."""
    cfg = Config()
    # Nominal RL (filter OFF)
    env_nom = CarFollowingEnv(config=cfg, mode="synthetic", use_cbf_filter=False, use_cbf_reward=False)
    env_nom.reset(seed=42)

    # Set up a state where policy action violates CBF:
    # Set high follower speed and small gap such that u_cbf_max is low
    env_nom.s = 30.0
    env_nom.v_ego = 20.0
    env_nom.v_lead = 18.0  # delta_v = -2.0 m/s
    # h = 30 - (2*20 + 15) = 30 - 55 = -25 m < 0
    # u_cbf_max = (-2.0 + 0.1 * (-25)) / 2.0 = (-2.0 - 2.5) / 2.0 = -2.25 m/s^2

    # Propose full throttle: a = 1.0 => u_policy = +2.5 m/s^2
    action = np.array([1.0], dtype=np.float32)
    _, _, _, _, step_info = env_nom.step(action)

    # Here u_safe will be clipped to -2.25 m/s^2
    assert step_info["u_safe"] == -2.25
    assert step_info["u_policy"] == 2.5
    assert step_info["u_applied"] == 2.5

    # Since Filter is OFF, nominal reward must use u_applied = +2.5, NOT u_safe = -2.25!
    assert step_info["u_for_nominal_reward"] == 2.5
    expected_r_ctrl = -cfg.w_ctrl * (2.5 / cfg.u_max) ** 2  # = -0.1 * 1.0 = -0.1
    assert abs(step_info["r_ctrl"] - expected_r_ctrl) < 1e-9, (
        f"Expected r_ctrl={expected_r_ctrl}, got {step_info['r_ctrl']}"
    )

    # If it had used u_safe (-2.25), r_ctrl would be -0.1 * (-2.25/2.5)^2 = -0.081
    r_ctrl_if_contaminated = -cfg.w_ctrl * (-2.25 / cfg.u_max) ** 2
    assert abs(step_info["r_ctrl"] - r_ctrl_if_contaminated) > 0.01, (
        "Nominal reward was contaminated with u_safe!"
    )
    print("PASS: test_ablation_filter_off_nominal_reward_isolation (u_safe does NOT leak into Filter OFF)")


def test_ablation_filter_on_nominal_reward():
    """Verify D: When Filter is ON, nominal reward uses the applied filtered action u_safe."""
    cfg = Config()
    # Filter Only (filter ON)
    env_filt = CarFollowingEnv(config=cfg, mode="synthetic", use_cbf_filter=True, use_cbf_reward=False)
    env_filt.reset(seed=42)

    # Replicate identical state:
    env_filt.s = 30.0
    env_filt.v_ego = 20.0
    env_filt.v_lead = 18.0

    action = np.array([1.0], dtype=np.float32)  # u_policy = +2.5
    _, _, _, _, step_info = env_filt.step(action)

    # Here u_safe = -2.25 m/s^2, and Filter is ON => u_applied = u_safe
    assert step_info["u_safe"] == -2.25
    assert step_info["u_applied"] == -2.25
    assert step_info["u_for_nominal_reward"] == -2.25

    expected_r_ctrl = -cfg.w_ctrl * (-2.25 / cfg.u_max) ** 2
    assert abs(step_info["r_ctrl"] - expected_r_ctrl) < 1e-9, (
        f"Expected r_ctrl={expected_r_ctrl}, got {step_info['r_ctrl']}"
    )
    print("PASS: test_ablation_filter_on_nominal_reward (Filter ON evaluates nominal reward with u_safe)")


def test_closed_loop_env_modes():
    """Verify all 4 ablation modes step correctly in synthetic and vicolungo modes."""
    cfg = Config()

    modes = [
        ("Nominal", False, False),
        ("Filter Only", True, False),
        ("Reward Only", False, True),
        ("Dual CBF-RL", True, True),
    ]

    for name, use_filt, use_rew in modes:
        env = CarFollowingEnv(
            config=cfg,
            mode="synthetic",
            use_cbf_filter=use_filt,
            use_cbf_reward=use_rew,
        )
        obs, info = env.reset(seed=42)
        assert obs.shape == (4,), f"Obs shape should be (4,), got {obs.shape}"
        assert not np.isnan(obs).any(), "NaN found in initial observation"

        # Step 10 times with arbitrary policy actions
        for i in range(10):
            action = np.array([0.5 if i % 2 == 0 else -0.5], dtype=np.float32)
            next_obs, reward, terminated, truncated, step_info = env.step(action)
            assert next_obs.shape == (4,)
            assert not np.isnan(reward), "NaN reward encountered"
            assert "is_intervened" in step_info
            assert "is_infeasible" in step_info
            assert "h" in step_info

            # Check that filter-only/dual actually filters when policy breaches CBF
            if use_filt and step_info["u_policy"] > step_info["u_cbf_max"]:
                assert step_info["u_applied"] == step_info["u_safe"]
                assert step_info["u_for_nominal_reward"] == step_info["u_safe"]
            elif not use_filt:
                # Nominal and Reward-Only apply policy action (clipped only by physical bounds)
                expected_u = max(cfg.u_min, min(cfg.u_max, step_info["u_policy"]))
                assert abs(step_info["u_applied"] - expected_u) < 1e-6
                assert abs(step_info["u_for_nominal_reward"] - expected_u) < 1e-6

            # Check that CBF reward is active only when use_cbf_reward is True
            if not use_rew:
                assert step_info["r_cbf"] == 0.0

        print(f"PASS: env ablation mode '{name}' (synthetic)")


if __name__ == "__main__":
    print("=" * 70)
    print("RUNNING PROTOTYPE 3 MATHEMATICAL & METHODOLOGICAL UNIT TESTS")
    print("=" * 70)
    test_safety_barrier_h()
    test_u_cbf_max()
    test_cbf_projection()
    test_actuator_infeasibility()
    test_discrete_dynamics()
    test_reward_calculation()
    test_vicolungo_exact_lead_replay()
    test_vicolungo_closed_loop_follower_independence()
    test_ablation_filter_off_nominal_reward_isolation()
    test_ablation_filter_on_nominal_reward()
    test_closed_loop_env_modes()
    print("=" * 70)
    print("ALL PROTOTYPE 3 MATHEMATICAL & METHODOLOGICAL UNIT TESTS PASSED!")
    print("=" * 70)
